#!/bin/bash


protected_branch='refs/heads/master1'
current_branch=$(git symbolic-ref HEAD) 

if [ $current_branch = $protected_branch ]
then 
	echo "you can't push to master1!"
	exit 1
else
	exit 0
fi
